import type { CharacterId } from "./characters";

// Provocações curtas por personagem (PT-BR, tom militar/canino, sem ofensa).
const CHALLENGES: Record<CharacterId, string[]> = {
  ranger: [
    "Disciplina vence instinto. Prepare-se.",
    "Missão simples: você no chão em 3 turnos.",
    "Sem rosnado. Só precisão.",
    "Treinei pra isso enquanto você dormia.",
    "Meu plano já venceu. Falta só executar.",
    "Respira fundo. Vai ser o último.",
    "Sou o silêncio antes do estouro.",
    "Cheiro medo daqui. Cheira bem.",
    "Manual página 1: você perde.",
    "Rango de biscoito com mais tática que você.",
  ],
  brutus: [
    "Late alto, morde mais alto.",
    "Vou te transformar em petisco.",
    "Trincheira é meu quintal, filhote.",
    "Casco duro. Mira dura. Chora dura.",
    "Sou parede. Você é o vento.",
    "Meu blindado abre a lata do seu ego.",
    "Rosna aí que eu já tô miserável.",
    "Sente o chão tremer? Sou eu andando.",
    "Meu vento derruba a sua tenda.",
    "Fim de jogo em cheiro de pólvora.",
  ],
  musa: [
    "Sou bruta, não bruta demais. Só o suficiente.",
    "Cheguei pra terminar antes do café.",
    "Meu soco chega antes do seu tiro.",
    "Estilo é minha primeira arma.",
    "Você mira. Eu já dancei em cima.",
    "Sem drama. Só pontaria.",
    "Vento é meu amigo — o seu, não.",
    "Curva bonita, tiro certeiro.",
    "Eu não erro. Eu ensaio.",
    "Fofo o discurso. Cadê o dano?",
  ],
  ozzy: [
    "Você mira. Eu já pulei.",
    "Rápido demais pra sua bomba.",
    "Traz o osso, filhote — se conseguir.",
    "Vou correr em volta enquanto explode.",
    "Duas patas no chão, quatro na vitória.",
    "Meu pulo é maior que o seu plano.",
    "Zunido no ar? Sou eu passando.",
    "Cronômetro: 10s pra você cair.",
    "Sou míssil de bolso.",
    "Ficha caindo... e você também.",
  ],
  negao: [
    "Reza, filhote. Hoje eu tô com fome.",
    "Vou te enterrar com honras. Ou sem.",
    "Cane Corso não late. Cane Corso encerra.",
    "Muralha ambulante chegando.",
    "Meu peito para bala. O seu, não.",
    "Sombra pesada. Passo pesado. Fim pesado.",
    "Rosnado grave, resultado óbvio.",
    "Sou o último som que você vai ouvir.",
    "Blindagem de veterano — não passa nada.",
    "Fim de linha. Sem estação, sem volta.",
  ],
  miu: [
    "Nove vidas. Você tem uma. Faz as contas.",
    "Purr… foi a última coisa que ele ouviu.",
    "Miau. Agora corre.",
    "Sombra. Silêncio. Sangue frio.",
    "Você olha. Eu já tô atrás.",
    "Passo felpudo, tiro certeiro.",
    "Sou o susto que vem depois do silêncio.",
    "Bigode alinhado, mira alinhada.",
    "Cai o pano. Cai você junto.",
    "Ronron letal. Trailer curto, filme rápido.",
  ],
  barto: [
    "Baixinho? Sim. Fraco? Pergunta pro último.",
    "Coração de leão em corpo de tanque.",
    "Quanto mais apanho, mais mordo.",
    "Cara de bobo, mordida de crocodilo.",
    "Meu ronco derruba parede.",
    "Chegou perto? Chegou tarde.",
    "Focinho curto, memória longa pra vingança.",
    "Vou te lamber no fim — depois de te apagar.",
    "Não corro. Espero. E fecho a boca.",
    "Bulldog francês, tática brasileira.",
  ],
};

const REPLIES: Record<CharacterId, string[]> = {
  ranger: [
    "Faça bonito. Ou faça rápido.",
    "Vamos ver esse plano em campo.",
    "Menos conversa. Mais tiro.",
    "Registrado. Refutado.",
    "Meu relatório já te aposentou.",
    "Concordo em discordar — na mira.",
    "Guarda a piada. Saca a bomba.",
    "Ordem é ordem. A sua é cair.",
    "Prova em campo, filhote.",
    "Aceito o desafio. Marca a lápide.",
  ],
  brutus: [
    "Rosnado bonito. Cadê a mordida?",
    "Cala a boca e atira.",
    "Vai chorar antes do terceiro turno.",
    "Rosno mais alto. Testa aí.",
    "Chega de conversa, chega de dente.",
    "Meu vento derruba tuas palavras.",
    "Barulhinho fofo. Explosão minha.",
    "Ronca outra vez que eu esqueci.",
    "Sente o coldre? É o teu fim.",
    "Late menos. Morde mais. Vou ensinar.",
  ],
  musa: [
    "Traz café pra dois, então.",
    "Vou te devolver na coleira.",
    "Cansei de conversa. Bora.",
    "Bonito o script. Ruim o final.",
    "Bota a mira. Eu já botei estilo.",
    "Dança comigo — última música.",
    "Mira boa, ego pequeno. Impossível.",
    "Meu curto-circuito é você tentar.",
    "Termina esse discurso, começa a chorar.",
    "Charme? Não. Precisão? Sempre.",
  ],
  ozzy: [
    "Pula alto. Cai mais alto.",
    "Corre, filhote. Só vai atrasar.",
    "Meu tiro te encontra no ar.",
    "Zunido de mosquito, dano de nada.",
    "Rápido no papo, lento na bomba.",
    "Salta de novo. Adoro alvo móvel.",
    "Você não voa. Vai descobrir.",
    "Meu cronômetro é mais curto que o seu.",
    "Dá voltas. Meu tiro é reto.",
    "Zoom teu, zoom meu. Vai perder.",
  ],
  negao: [
    "Ronca à vontade. Vou calar na primeira.",
    "Traz reforço. Vai precisar.",
    "Fica quieto que dói menos.",
    "Muralha? Vou virar entulho.",
    "Sombra grande, alvo grande.",
    "Peso extra: falha extra.",
    "Blindado demais pra correr. Ruim pra você.",
    "Passo pesado é passo previsível.",
    "Últimas palavras? Escolhe direito.",
    "Fim de linha? A sua, chefe.",
  ],
  miu: [
    "Fofo. Agora explode.",
    "Bonitinho o discurso. Ridículo o tiro.",
    "Fecha o olho. Melhor assim.",
    "Ronron cansado. Bomba nova.",
    "Nove vidas? Vou tirar oito.",
    "Sombra pequena. Ego enorme.",
    "Silêncio bonito. Grito melhor.",
    "Miau seu. Trovão meu.",
    "Bigode teu, coleira minha.",
    "Termina o filme, felina — vou dar spoiler.",
  ],
  barto: [
    "Rosna bonito. Vai chorar feio.",
    "Fofo eu não sou. Nem tento.",
    "Fecha o cerco que eu fecho a boca.",
    "Chega pertinho. Adoro trabalho de perto.",
    "Cansei do papo. Bora no dente.",
    "Meu ronco é aviso. O próximo é fim.",
    "Vem, filhote. Tio Bartô cuida.",
    "Ri de mim? Ri sem dente depois.",
    "Meu peito aguenta. O teu, veremos.",
    "Baixinho tem o quê? Fôlego. E raiva.",
  ],
};

// Determinístico por par + índice de mistura, com uma pitada aleatória.
export function pickDialogue(a: CharacterId, b: CharacterId): { challenge: string; reply: string } {
  const ch = CHALLENGES[a];
  const rp = REPLIES[b];
  const seed = (a.length * 7 + b.length * 13 + Math.floor(Math.random() * 9999)) | 0;
  return {
    challenge: ch[seed % ch.length],
    reply: rp[(seed >> 3) % rp.length],
  };
}
