/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignIndexRouteImport } from './routes/campaign.index'
import { Route as MatchCodeRouteImport } from './routes/match.$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as CampaignMissionIdRouteImport } from './routes/campaign.$missionId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIndexRoute = CampaignIndexRouteImport.update({
  id: '/campaign/',
  path: '/campaign/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchCodeRoute = MatchCodeRouteImport.update({
  id: '/match/$code',
  path: '/match/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignMissionIdRoute = CampaignMissionIdRouteImport.update({
  id: '/campaign/$missionId',
  path: '/campaign/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/online': typeof OnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/campaign/$missionId': typeof CampaignMissionIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/match/$code': typeof MatchCodeRoute
  '/campaign/': typeof CampaignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/online': typeof OnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/campaign/$missionId': typeof CampaignMissionIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/match/$code': typeof MatchCodeRoute
  '/campaign': typeof CampaignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/online': typeof OnlineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/campaign/$missionId': typeof CampaignMissionIdRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/match/$code': typeof MatchCodeRoute
  '/campaign/': typeof CampaignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/online'
    | '/sitemap.xml'
    | '/campaign/$missionId'
    | '/lobby/$code'
    | '/match/$code'
    | '/campaign/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/online'
    | '/sitemap.xml'
    | '/campaign/$missionId'
    | '/lobby/$code'
    | '/match/$code'
    | '/campaign'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/online'
    | '/sitemap.xml'
    | '/campaign/$missionId'
    | '/lobby/$code'
    | '/match/$code'
    | '/campaign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OnlineRoute: typeof OnlineRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CampaignMissionIdRoute: typeof CampaignMissionIdRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  MatchCodeRoute: typeof MatchCodeRoute
  CampaignIndexRoute: typeof CampaignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/': {
      id: '/campaign/'
      path: '/campaign'
      fullPath: '/campaign/'
      preLoaderRoute: typeof CampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$code': {
      id: '/match/$code'
      path: '/match/$code'
      fullPath: '/match/$code'
      preLoaderRoute: typeof MatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$missionId': {
      id: '/campaign/$missionId'
      path: '/campaign/$missionId'
      fullPath: '/campaign/$missionId'
      preLoaderRoute: typeof CampaignMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OnlineRoute: OnlineRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CampaignMissionIdRoute: CampaignMissionIdRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  MatchCodeRoute: MatchCodeRoute,
  CampaignIndexRoute: CampaignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
