ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS world_w integer NOT NULL DEFAULT 1280,
  ADD COLUMN IF NOT EXISTS world_h integer NOT NULL DEFAULT 720,
  ADD COLUMN IF NOT EXISTS current_slot integer NOT NULL DEFAULT 0;